# See https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md
dependencies:
  - name: oauth2-proxy
    version: "0.11.0"
    repository: "https://kubernetes-charts.storage.googleapis.com"
