# Default values for oauth2-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# The outh2 proxy service that will handle communication with the oauth2 provider
oauth2ProxyService:
  # Name for the service. Must match the value set for oauth2-proxy.fullnameOverride
  name: &proxyServiceName "sample-oauth2-proxy"
  # Port the service listens on. Must match the value set for oauth2-proxy.service.port
  port: &proxyServicePort 80

# This ingress definition is the one that is web facing for the protected service
ingress:
  # Host for this ingress
  host: protected.ninedemons.io

  # These paths should be for the service that you want to restrict access to
  paths:
    - backend:
        serviceName: protected-service
        servicePort: web
      path: /

  tls:
    - hosts:
        - protected.ninedemons.io
      secretName: protected.ninedemons.io-tls

# The oauth2-proxy handles communication with the oauth2 provider and handing over user details to
# the protected service
oauth2-proxy:
  fullnameOverride: *proxyServiceName
  service:
    port: *proxyServicePort
  extraArgs:
    provider: "github"

    # Github specific config - see https://github.com/bitly/oauth2_proxy#github-auth-provider
    github-org: "ninedemons"
    github-team: "engineering"
    email-domain: "*"
    set-xauthrequest: "true"

  # Oauth client configuration specifics
  config:
    # OAuth client ID
    clientID: "XXXXXXX"
    # OAuth client secret
    clientSecret: "XXXXXXXX"
    # Create a new secret with the following command
    # openssl rand -base64 32 | head -c 32 | base64
    # existingSecret: secret
    cookieSecret: "XXXXXXXXXX"
