# This task runs slow tests for the chart. These are typically tests that deploy
# to a k8s instance

---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ninedemons/go_helm
    tag: v3.3.0_1.14

params:
  GOCACHE: /tmp/build/cache # Used for go build caching


inputs:
  - name: chart_archive
  - name: source

caches:
  - path: gopath/

run:
  path: /bin/sh
  args:
    - -exec
    - |

      echo "Deploy to a kubernetes cluster"
      sleep 30
      echo "Run acceptance tests"
      sleep 2m

