# This ingress sits in front of the oauth2 service for the handshake with github
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy-{{ include "oauth2-ingress.fullname" . }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.oauth2ProxyService.name }}
              servicePort: {{ .Values.oauth2ProxyService.port }}
            path: /oauth2

